### ISSUE TITLE
Add to Decky store

### ISSUE THREAD

**Issue by nihaals** [EmuDeck/emudeck-decky-controls#3]
It would be great if the plugin was in the [Decky plugin store](https://github.com/SteamDeckHomebrew/decky-plugin-database) to make it simpler to install and update.

**Comment by dragoonDorise** [comment]
Hi @nihaals , we've revamped this plugin and besides doing more stuff now... we have submitted it to the Decky Store! As soon as it's published, we will update everybody using our Patreon.
