### ISSUE TITLE
Plugin does not work without internet

### ISSUE THREAD

**Issue by karasuhebi** [EmuDeck/emudeck-decky-controls#4]
Given that the Steam Deck is a portable device, it's reasonable to assume it will be used without internet access at times.

Is there any way to make it so that this plugin can load the pictures of the different hotkeys for the different systems from a file instead of from the internet?

**Comment by dragoonDorise** [comment]
Hi @karasuhebi , we just asked Decky to publish our plugin, now all the hotkeys will be stored locally so it can work with no internet :)

I'll let know all the patrons on Patreon as soon as it's published on Decky.

**Comment by karasuhebi** [comment]
Are you referring to the new EmuDecky plugin? Or an updated version of this plugin?
